#!/usr/bin/sh
# Check for trailing whitespace
for file in $(git diff --cached --name-only | grep -E '\.(js|ts)$'); do
  if grep -q '[[:space:]]$' "$file"; then
    echo "Trailing whitespace found in $file"
    exit 1
  fi
done

# check js and ts with biome
npx biome check $(git diff --cached --name-only | grep -E '\.(js|ts)$') --write
if [ $? -ne 0 ]; then
  echo "check errors found"
  exit 1
fi

